### PR TITLE
first take at filetypes

### PR DESCRIPTION
**Pull request by derekxkwan**
docu is really vague,.. something about 4 letter combos corresponding to 3 letter extensions (maybe that was another object)? so mostly a guessing game here...  so i made "filetype csv" (i know, only 3 letters, but how you make it 4?) set extension ".csv" and "filetype text" set extension ".txt", anything else unsets extension

think i got the max length for strncpy correct maxpdstring - 5

### CODE REVIEW

**Comment by porres** [comment]
my guess is that the user specifies whatever he wants as a file extension, anything arbitrary or not, like ".dek", ".fft", and whatever is in coll just gets saved with that file extension

**Comment by porres** [comment]
anyway, trying your Pull Request, any "write" message blows up Pd :)

**Comment by derekxkwan** [comment]
hmm, when does this happen? trying with args and seems to work okay, with both write with no args (works as it did before) and write with args, need to implement filetype with no args though...

**Comment by porres** [comment]
> when does this happen?

anytime I try a write message. Just opening the help file and trying the "write coll.txt" message in the help examples blows up Pd for me... this doesn't happen for the last stable release

**Comment by porres** [comment]
about how filetype doesn't work in Max... just tested with the new Max 8 trial...

**Comment by porres** [comment]
oops, here it is: https://github.com/porres/pd-cyclone/issues/438

**Pull request merged**
