### PR TITLE
Fixed symbol conflicts with ELSE, fixed MSVC compilation of funbuff

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by porres** [comment]
Tim, may you exclude cyclone's pink and just use the one from else?

**Comment by porres** [comment]
Or is it q problem when using cyclone/pink~?

**Comment by timothyschoen** [comment]
It's a problem in general to have functions with the same name in both ELSE and cyclone, because Pd will always use the function that was loaded first. So if there are any implementation differences between the two at some point, that could lead to strange problems. And of course it's necessary for it to compile in plugdata. And yeah, you can use both [else/pink~] and [cyclone/pink~] in plugdata.

**Comment by porres** [comment]
> So if there are any implementation differences between the two at some point, that could lead to strange problems.

they are exactly the same! Only issue I can think of is if someone is using [cyclone/pink~]

**Pull request merged**
